# Docker Compose para subir as aplicações abaixo:
# * Giropops-senhas
# * Redis
# * Nginx
# Autor: Bruno Salmito
# Versão do arquivo: 1.0
# --------------------------------------------------

services:
# ==================================================
# APP: Giropops-senhas
# Version: 1.0
  giropops-senhas:
    container_name: giropops_app
    build:
      context: ./Build
      dockerfile: Dockerfile
    networks:
      rede_app:
        ipv4_address: 172.25.0.5
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis_server
    volumes:
      - type: volume
        source: volume
        target: /volume
    deploy:
      labels:
        intranet.casa.description: 'Giropops APP'
        intranet.casa.version: '1.0'
      #replicas: 4
      update_config:
        parallelism: 2
        delay: 30s
      resources:
        reservations:
          cpus: '0.25'
          memory: 16m
        limits:
          cpus: '0.5'
          memory: 32m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "python", "check.py"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - redis
#================================================
# APP: Redis
# Version:
#================================================
  redis:
    image: redis:latest
    container_name: redis_server
    networks:
      rede_app:
        ipv4_address: 172.25.0.6
    ports:
      - '6379:6379'
    volumes:
      - type: volume
        source: redis_data
        target: /data
    deploy:
      labels:
        intranet.casa.description: "Redis server, usado para salvar os dados da aplicação"
        intranet.casa.version: "1.0"
      #replicas: 4
      update_config:
        parallelism: 2
        delay: 30s
      resources:
        reservations:
          cpus: '0.25'
          memory: 16m
        limits:
          cpus: '0.50'
          memory: 32m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
#================================================
volumes:
  volume:
  redis_data:

networks:
  rede_app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          ip_range: "172.25.0.0/16"
          gateway: "172.25.0.1"